apiVersion: v1
kind: Service
metadata:
  name: db # this name will be used for the apps which depends on the database
  labels:
    name: postgres-service
    app: demo-voting-app
spec:
  ports:
    - port: 5432
      targetPort: 5432
  selector:
    name: postgres-pod
    app: demo-voting-app
